# Generated by Django 3.0.6 on 2020-06-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcd',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pcb_id', models.AutoField(primary_key=True, serialize=False)),
                ('pcd_url', models.ImageField(upload_to='')),
                ('pcd_name', models.CharField(max_length=256, null=True)),
                ('pcd_uuid', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'pcd',
            },
        ),
    ]
