# Generated by Django 3.0.6 on 2020-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcd',
            name='pcd_url',
            field=models.CharField(max_length=256),
        ),
    ]
