# Generated by Django 3.0.6 on 2020-06-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200615_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcd',
            name='pcd_name',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcd',
            name='pcd_url',
            field=models.CharField(max_length=500),
        ),
    ]
