# Generated by Django 3.0.6 on 2020-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200615_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcd',
            name='pcd_name',
            field=models.CharField(default='xx.pcd', max_length=128),
        ),
        migrations.AlterField(
            model_name='pcd',
            name='pcd_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pcd',
            name='pcd_uuid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
